
alice_blue = 'E8EEF2'
black_coral = '8D99AE'
cornsilk = 'F1ECCE'
coyote = '7A542E'
dark_green = '3A5743'
dark_lava = '463F3A'
dark_purple = '331832'
hunter_green = '60A561'
isabeline = 'F4F3EE'
queen_blue = '33658A'
rhythm = '777FA8'
