
alice_blue = 'E8EEF2'
amazon_green = '496E55'
black_coral = '8D99AE'
cornsilk = 'F1ECCE'
coyote = '7A542E'
dark_green = '3A5743'
dark_lava = '463F3A'
dark_liver_horses = '583836'
dark_purple = '331832'
hunter_green = '60A561'
independence = '5D576B'
indigo_dye = '00487C'
isabeline = 'F4F3EE'
queen_blue = '33658A'
rhythm = '777FA8'
snow = 'FCF7F8'
