
party = ['@', 'snow']

[landmarks]
cave = ['o', 'coyote']
settlement = ['^', 'moutain_peaks']

[terrains]
hills = ['~', 'coyote']
moutain_peaks = ['^', 'alice_blue']
mountains = ['^', 'black_coral']
plains = ['"', 'hunter_green']
water = ['=', 'queen_blue']
woods = ['&', 'dark_green']
