
# Landmarks
[landmarks]
cave = ['o', 'black_coral']
settlement = ['^', 'moutain_peaks']

# Terrains
[terrains]
hills = ['~', 'coyote']
moutain_peaks = ['^', 'alice_blue']
mountains = ['^', 'black_coral']
plains = ['"', 'hunter_green']
water = ['=', 'queen_blue']
woods = ['&', 'dark_green']
