fallback = ['?', 'alice_blue']

[biomes]
hills = ['~', 'coyote']
mountains = ['^', 'black_coral']
plains = ['"', 'hunter_green']
water = ['=', 'queen_blue']
woods = ['&', 'dark_green']
woods__broadleaf = ['&', 'amazon_green']
woods__evergreen = ['&', 'dark_green']
woods__evergreen__ancient = ['%', 'dark_green']

[creatures]
dwarf = ['D', 'snow']
goblin = ['g', 'indigo_dye']
human = ['H', 'snow']
rat = ['r', 'dark_liver_horses']

[scenary]
stone_wall = ['#', 'black_coral']
tree = ['&', 'dark_green']

[items]
short_sword = ['(', 'black_coral']

[landmarks]
cave = ['O', 'black_coral']

[parties]
player = ['@', 'snow']

[terrain]
earth = ['~', 'coyote']
stone = ['*', 'black_coral']
grass = ["'", 'hunter_green']
grass__long = ['"', 'hunter_green']

