
display = [120, 40]
display_resizable = false

# Color theme
bg_color = 'dark_purple'
fg_color = 'cornsilk'
primary_button_color = 'rhythm'

[console]
    bg_color = 'dark_lava'
    fg_color = 'isabeline'
    scroll_up_down = 34 # page down
    scroll_up_char = 33 # page up
    toggle_char = 96 # `
